version: '3'
services:
    nginx:
        build:
            context: ./
            dockerfile: dockerfiles/nginx/nginx.docker
        volumes:
            - './:/var/www'
        restart: always
        ports:
            - '8001:80'
        links:
            - php
    php:
        build:
            context: ./
            dockerfile: dockerfiles/php/php.docker
        volumes:
            - './:/var/www'
        restart: always
        links:
            - redis
        environment:
            - "TZ=America/Guatemala"
            - CONTAINER_ROLE=app
    redis:
        build:
            context: ./
            dockerfile: dockerfiles/redis/redis.docker
        restart: always
    scheduler:
        build:
            context: ./
            dockerfile: dockerfiles/php/php.docker
        volumes:
            - './:/var/www'
        restart: always
        environment:
            - "TZ=America/Guatemala"
            - CONTAINER_ROLE=scheduler
        links: 
            - redis
    horizon:
        build:
            context: ./
            dockerfile: dockerfiles/php/php.docker
        volumes:
            - './:/var/www'
        restart: always
        environment:
            - "TZ=America/Guatemala"
            - CONTAINER_ROLE=horizon
        links:
            - redis